sudo: false
language: rust
cache: cargo
rust:
  - nightly
  - beta
  - stable
  - 1.36.0 # currently oldest supported version
os:
  - linux
  - windows
  - osx
script:
  - cargo build --verbose
  - cargo test --verbose
